Repository MIT-Emerging-Talent/2024-group-01-cdsp, pull requests merged in 2024-02, with the labels that each got.

#4 Draft of README.md
  README.md
Labels: documentation, enhancement

#7 Retrospective Milestone 2.md
  .collaboration/Retrospective Milestone 2.md
Labels: documentation

#6 Domain modelling
  README.md
Labels: documentation

#9 Agriculture and Urbanization Data Analysis
  Agriculture and Urbanization Analysis.ipynb
Labels: enhancement
